### PR TITLE
doc: demo install

### PR DESCRIPTION
**Pull request by desaxce**
### Changes:
- added doc on submodule update
- added error faced on npm start, documented demo `npm install`

### CODE REVIEW

**Comment by joneugster** [comment]
Thanks for testing and for the PR!

Regaring the second error, I updated `demo/package-lock.json` and added `(cd demo && npm install)` to the command `npm start`.

Hopefully that should fix it. Would you mind testing and confirming?

**Comment by desaxce** [comment]
Thanks! On Linux (6.6.41-1-MANJARO) I have an error upon running `npm start` the first time:
```
[vite] Error:   Failed to scan for dependencies from entries:
[vite]   /home/precision/tmp/lean4monaco/demo/index.html
[vite] 
[vite]   ✘ [ERROR] Failed to resolve entry for package "lean4monaco". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]
[vite] 
[vite]     node_modules/vite/node_modules/esbuild/lib/main.js:1225:21:
[vite]       1225 │         let result = await callback({
[vite]            ╵                      ^
[vite] 
[vite]     at packageEntryFailure (file:///home/precision/tmp/lean4monaco/demo/node_modules/vite/dist/node/chunks/dep-Cy9twKMn.js:46533:15)
```

Seems to be `vite` launching a little too early, I have no errors on subsequent runs of `npm start`. 

On Mac Sonoma, still facing integrity discrepancies:

**Comment by joneugster** [comment]
I updated the repo once again, hopefully addressing everything from this PR!

I also added CI for linux/macOS/Windows. The latter two are failing currently, but hopefully I can get them to work eventually.

**Comment by joneugster** [comment]
Thanks for the feedback! If you experience any further problems, please reach out again!

**Pull request closed without merging**
